import nodemailer from "nodemailer";

interface MailConfig {
  host: string;
  port: number;
  secure: boolean;
  user: string;
  pass: string;
  fromAddress: string;
  fromName: string;
}

function getMailConfig(): MailConfig | null {
  const host = process.env.SMTP_HOST?.trim();
  const user = process.env.SMTP_USER?.trim();
  const pass = process.env.SMTP_PASS;
  if (!host || !user || !pass) return null;

  const configuredPort = Number(process.env.SMTP_PORT ?? "587");
  const port = Number.isInteger(configuredPort) && configuredPort > 0 && configuredPort <= 65535
    ? configuredPort
    : 587;

  return {
    host,
    port,
    secure: process.env.SMTP_SECURE === "true",
    user,
    pass,
    fromAddress: process.env.SMTP_FROM?.trim() || user,
    fromName: process.env.SMTP_FROM_NAME?.trim() || "Occu-Med PacketPath",
  };
}

export function buildSmtpTransportOptions(cfg: MailConfig) {
  return {
    host: cfg.host,
    port: cfg.port,
    secure: cfg.secure,
    // Port 587 begins as a plaintext SMTP connection. requireTLS prevents
    // delivery if the server cannot upgrade the connection with STARTTLS.
    requireTLS: !cfg.secure,
    auth: { user: cfg.user, pass: cfg.pass },
    // Validate the server certificate and reject legacy TLS versions.
    tls: {
      rejectUnauthorized: true,
      minVersion: "TLSv1.2" as const,
    },
    // Email bodies are fully generated by PacketPath. Prevent Nodemailer from
    // resolving file:// paths or fetching remote URLs embedded as attachments.
    disableFileAccess: true,
    disableUrlAccess: true,
  };
}

function createTransport(cfg: MailConfig) {
  return nodemailer.createTransport(buildSmtpTransportOptions(cfg));
}

function htmlEscape(value: string): string {
  return value
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;")
    .replaceAll("'", "&#039;");
}

function signingEmailHtml({
  recipientName,
  senderName,
  requestTitle,
  message,
  signingUrl,
  expiresAt,
  isReminder,
}: {
  recipientName: string;
  senderName: string;
  requestTitle: string;
  message: string | null;
  signingUrl: string;
  expiresAt: Date | null;
  isReminder: boolean;
}) {
  const expiry = expiresAt
    ? expiresAt.toLocaleDateString("en-US", { weekday: "long", year: "numeric", month: "long", day: "numeric" })
    : "7 days from now";
  const safeRecipient = htmlEscape(recipientName);
  const safeSender = htmlEscape(senderName);
  const safeTitle = htmlEscape(requestTitle);
  const safeMessage = message ? htmlEscape(message) : null;
  const safeUrl = htmlEscape(signingUrl);

  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8" />
<meta name="viewport" content="width=device-width, initial-scale=1.0" />
<title>${isReminder ? "Reminder: " : ""}Please Sign: ${safeTitle}</title>
<style>
  * { box-sizing: border-box; }
  body { margin: 0; padding: 32px 16px; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; background: #f0f4f8; color: #1e293b; }
  .wrapper { max-width: 560px; margin: 0 auto; }
  .card { background: #ffffff; border-radius: 16px; overflow: hidden; box-shadow: 0 4px 24px rgba(0,0,0,0.08); }
  .header { background: linear-gradient(135deg, #3b4fce 0%, #7c3aed 100%); padding: 32px 40px; color: #ffffff; }
  .brand { font-size: 14px; font-weight: 700; opacity: .9; margin-bottom: 20px; }
  .header h1 { margin: 0; font-size: 22px; line-height: 1.3; }
  .header p { margin: 8px 0 0; color: rgba(255,255,255,.75); font-size: 14px; }
  .body { padding: 36px 40px; }
  .greeting { margin: 0 0 12px; font-size: 17px; font-weight: 700; color: #0f172a; }
  .text { margin: 0 0 18px; font-size: 14px; line-height: 1.7; color: #475569; }
  .doc { margin: 22px 0; padding: 16px 20px; border: 1px solid #e2e8f0; border-radius: 12px; background: #f8fafc; }
  .doc-label { font-size: 11px; font-weight: 700; color: #94a3b8; text-transform: uppercase; letter-spacing: .08em; }
  .doc-title { margin-top: 6px; font-size: 15px; font-weight: 700; color: #0f172a; }
  .doc-msg { margin-top: 7px; font-size: 13px; color: #64748b; font-style: italic; }
  .btn-wrap { margin: 28px 0; text-align: center; }
  .btn { display: inline-block; padding: 15px 34px; border-radius: 12px; background: linear-gradient(135deg, #4f63e7, #7c3aed); color: #fff !important; text-decoration: none; font-size: 15px; font-weight: 700; }
  .link-box { margin: 0 0 22px; padding: 12px 16px; border: 1px solid #e2e8f0; border-radius: 8px; background: #f1f5f9; }
  .link-label { margin-bottom: 4px; font-size: 11px; font-weight: 700; color: #94a3b8; text-transform: uppercase; }
  .link-url { font-family: monospace; font-size: 12px; color: #4f63e7; word-break: break-all; }
  .expiry { margin: 0 0 22px; padding: 12px 16px; border: 1px solid #fde68a; border-radius: 10px; background: #fffbeb; color: #92400e; font-size: 13px; }
  .security { margin-top: 26px; padding-top: 22px; border-top: 1px solid #e2e8f0; }
  .security-title { margin-bottom: 10px; font-size: 11px; font-weight: 700; color: #64748b; text-transform: uppercase; letter-spacing: .08em; }
  .badges { display: flex; flex-wrap: wrap; gap: 8px; }
  .badge { padding: 5px 10px; border: 1px solid #bbf7d0; border-radius: 999px; background: #f0fdf4; color: #166534; font-size: 11px; font-weight: 600; }
  .footer { padding: 20px 40px; border-top: 1px solid #e2e8f0; background: #f8fafc; color: #94a3b8; text-align: center; font-size: 12px; line-height: 1.6; }
</style>
</head>
<body>
<div class="wrapper">
  <div class="card">
    <div class="header">
      <div class="brand">PacketPath · Occu-Med E-Signatures</div>
      <h1>${isReminder ? "Your signature is still needed" : "You have a document to sign"}</h1>
      <p>${safeSender} has ${isReminder ? "resent" : "sent"} you a document for electronic signature.</p>
    </div>
    <div class="body">
      <p class="greeting">Hello, ${safeRecipient}</p>
      <p class="text">${isReminder
        ? "This is a reminder that the document below is still awaiting your signature. Please review and sign at your earliest convenience."
        : `${safeSender} from Occu-Med Occupational Health has sent you a document that requires your electronic signature. Please review it carefully before signing.`
      }</p>
      <div class="doc">
        <div class="doc-label">Document</div>
        <div class="doc-title">${safeTitle}</div>
        ${safeMessage ? `<div class="doc-msg">“${safeMessage}”</div>` : ""}
      </div>
      <div class="btn-wrap"><a href="${safeUrl}" class="btn">Review &amp; Sign Document →</a></div>
      <div class="link-box">
        <div class="link-label">Or copy this link into your browser</div>
        <div class="link-url">${safeUrl}</div>
      </div>
      ${expiresAt ? `<div class="expiry"><strong>This link expires on ${expiry}.</strong> After that, contact the sender for a new link.</div>` : ""}
      <div class="security">
        <div class="security-title">Security controls</div>
        <div class="badges">
          <div class="badge">✓ Electronic Consent</div>
          <div class="badge">✓ Secure Delivery</div>
          <div class="badge">✓ Encrypted in Transit</div>
          <div class="badge">✓ Audit Trail</div>
        </div>
      </div>
    </div>
    <div class="footer">
      This email was sent by Occu-Med Occupational Health via PacketPath.<br />
      If you did not expect this email, you may safely ignore it.
    </div>
  </div>
</div>
</body>
</html>`;
}

function signingEmailText({
  recipientName,
  senderName,
  requestTitle,
  message,
  signingUrl,
  expiresAt,
  isReminder,
}: {
  recipientName: string;
  senderName: string;
  requestTitle: string;
  message: string | null;
  signingUrl: string;
  expiresAt: Date | null;
  isReminder: boolean;
}) {
  const expiry = expiresAt
    ? expiresAt.toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" })
    : null;

  return [
    `Hello ${recipientName},`,
    "",
    isReminder
      ? "This is a reminder that the following document still requires your signature:"
      : `${senderName} from Occu-Med Occupational Health has sent you a document to sign:`,
    "",
    `Document: ${requestTitle}`,
    message ? `Message: "${message}"` : "",
    "",
    "Secure signing link:",
    signingUrl,
    "",
    expiry ? `This link expires on ${expiry}.` : "",
    "",
    "If you did not expect this email, you may safely ignore it.",
    "",
    "-- Occu-Med Occupational Health via PacketPath",
  ].filter(Boolean).join("\n");
}

export interface SendSigningEmailParams {
  recipientName: string;
  recipientEmail: string;
  senderName: string;
  requestTitle: string;
  message: string | null;
  signingToken: string;
  expiresAt: Date | null;
  isReminder?: boolean;
  baseUrl: string;
}

export async function sendSigningEmail(params: SendSigningEmailParams): Promise<{ sent: boolean; error?: string }> {
  const cfg = getMailConfig();
  if (!cfg) {
    return { sent: false, error: "SMTP not configured — set SMTP_HOST, SMTP_USER, SMTP_PASS environment variables" };
  }

  const {
    recipientName,
    recipientEmail,
    senderName,
    requestTitle,
    message,
    signingToken,
    expiresAt,
    isReminder = false,
    baseUrl,
  } = params;
  const signingUrl = `${baseUrl}/sign/${signingToken}`;
  const html = signingEmailHtml({ recipientName, senderName, requestTitle, message, signingUrl, expiresAt, isReminder });
  const text = signingEmailText({ recipientName, senderName, requestTitle, message, signingUrl, expiresAt, isReminder });

  try {
    const transport = createTransport(cfg);
    await transport.sendMail({
      from: `"${cfg.fromName}" <${cfg.fromAddress}>`,
      to: `"${recipientName}" <${recipientEmail}>`,
      subject: isReminder
        ? `Reminder: Occu-Med Secure Document Request — ${requestTitle}`
        : "Occu-Med Secure Document Request",
      html,
      text,
    });
    return { sent: true };
  } catch (err: any) {
    return { sent: false, error: err?.message ?? "Email send failed" };
  }
}

export async function verifySmtpConnection(): Promise<{ ok: boolean; error?: string }> {
  const cfg = getMailConfig();
  if (!cfg) return { ok: false, error: "SMTP not configured" };

  try {
    const transport = createTransport(cfg);
    await transport.verify();
    return { ok: true };
  } catch (err: any) {
    return { ok: false, error: err?.message ?? "Connection failed" };
  }
}

export function isEmailConfigured(): boolean {
  return Boolean(process.env.SMTP_HOST?.trim() && process.env.SMTP_USER?.trim() && process.env.SMTP_PASS);
}

export interface SendProgressSaveEmailParams {
  recipientName: string;
  recipientEmail: string;
  requestTitle: string;
  resumeUrl: string;
  expiresAt: Date;
}

export async function sendProgressSaveEmail(params: SendProgressSaveEmailParams): Promise<{ sent: boolean; error?: string }> {
  const cfg = getMailConfig();
  if (!cfg) return { sent: false, error: "SMTP not configured" };

  const { recipientName, recipientEmail, requestTitle, resumeUrl, expiresAt } = params;
  const expiry = expiresAt.toLocaleDateString("en-US", { weekday: "long", year: "numeric", month: "long", day: "numeric" });
  const safeRecipient = htmlEscape(recipientName);
  const safeTitle = htmlEscape(requestTitle);
  const safeResumeUrl = htmlEscape(resumeUrl);

  const html = `<!DOCTYPE html><html lang="en"><body style="font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif;background:#f8fafc;margin:0;padding:24px;">
<div style="max-width:560px;margin:0 auto;background:#fff;border-radius:12px;padding:32px;box-shadow:0 1px 3px rgba(0,0,0,.1);">
  <h2 style="color:#1e293b;margin-top:0;">Your progress has been saved</h2>
  <p style="color:#475569;">Hello ${safeRecipient},</p>
  <p style="color:#475569;">Your progress on <strong>“${safeTitle}”</strong> has been saved. You can return to complete it before the link expires.</p>
  <div style="text-align:center;margin:32px 0;"><a href="${safeResumeUrl}" style="background:#2563eb;color:#fff;padding:14px 28px;border-radius:8px;text-decoration:none;font-weight:600;display:inline-block;">Resume Where I Left Off →</a></div>
  <p style="color:#94a3b8;font-size:13px;">This resume link expires on <strong>${expiry}</strong>.</p>
  <hr style="border:none;border-top:1px solid #e2e8f0;margin:24px 0;" />
  <p style="color:#94a3b8;font-size:12px;">Sent securely by PacketPath · Occu-Med Occupational Health</p>
</div></body></html>`;

  try {
    const transport = createTransport(cfg);
    await transport.sendMail({
      from: `"${cfg.fromName}" <${cfg.fromAddress}>`,
      to: `"${recipientName}" <${recipientEmail}>`,
      subject: `Your progress on "${requestTitle}" has been saved`,
      html,
      text: `Hello ${recipientName},\n\nYour progress on "${requestTitle}" has been saved.\n\nResume here: ${resumeUrl}\n\nThis link expires on ${expiry}.\n\n-- Occu-Med Occupational Health via PacketPath`,
    });
    return { sent: true };
  } catch (err: any) {
    return { sent: false, error: err?.message ?? "Email send failed" };
  }
}
