import { branch, date, form, history, q, select, text } from "./definition-helpers";

const S = "Medical History";
const h = (key: string, label: string, prompts: string[]) => history(key, `${key} — ${label}`, S, prompts);

const pregnancy = history(
  "21",
  "21 — Are you pregnant?",
  S,
  [
    "Are you currently pregnant?",
    "Are you under current medical care?",
    "Are there any provider restrictions, limitations, or monitoring needs related to the pregnancy?",
  ],
  { statusGate: false },
);

export const ds1843Definition = form(
  "ds-1843-medical-history-examination",
  "DS-1843 — Medical History and Examination (Age 12 and Older)",
  "Adaptive examinee history for DS-1843, using the source-form numbering and the recovered condition-specific follow-up bank.",
  "U.S. Department of State DS-1843, 12-2023",
  [
    text("demo.name", "1a — Name of examinee (Last, First, MI)", "Demographic Information", false),
    text("demo.chosenName", "1b — Chosen name of examinee", "Demographic Information", false),
    text("demo.eligibleFamilyMember", "2 — If Eligible Family Member, name of employee/applicant", "Demographic Information", false),
    date("demo.dob", "3 — Date of birth", "Demographic Information", false),
    text("demo.birthplace", "4 — Place of birth (City, State, Country)", "Demographic Information", false),
    select("demo.sexAssignedAtBirth", "5b — Sex assigned at birth", "Demographic Information", ["Male", "Female"], false),
    q(
      "demo.pregnancyGate",
      "Pregnancy question applicability",
      "Demographic Information",
      { answerType: "dropdown", options: ["Not applicable", "Ask pregnancy question"], required: false, triggerValue: "ask pregnancy question", helpText: "Use when the pregnancy item on the source form applies." },
      [pregnancy],
    ),
    select("demo.status", "6 — Status", "Demographic Information", ["New Family Member", "Dependent Child", "Spouse", "Applicant", "Employee"], false),
    text("demo.agency", "7 — Agency of employee/applicant/sponsor", "Demographic Information", false),
    text("demo.healthPlan", "8 — Health insurance plan", "Demographic Information", false),
    select("demo.purpose", "9 — Purpose of exam", "Demographic Information", ["Pre-Employment Exam", "In-Service Exam", "Separation Exam"], false),
    text("demo.employmentStatus", "10 — Employment status", "Demographic Information", false),
    text("demo.email", "11 — Email address", "Demographic Information", false),
    text("demo.phone", "12 — Telephone number", "Demographic Information", false),
    text("demo.specialAssignment", "13 — Special assignment, if applicable", "Demographic Information", false),
    text("demo.post", "14 — Post of assignment and estimated dates", "Demographic Information", false),

    h("1", "Frequent/severe headaches or migraines?", [
      "Do you experience headaches, migraines, or both?",
      "How often do they occur and how severe are they?",
      "Are there known triggers?",
      "Are you receiving treatment or taking medication?",
      "Do they affect your daily activities or work?",
    ]),
    h("2", "Fainting, dizzy episodes, or syncope?", [
      "Are you referring to fainting, dizziness, syncope, or more than one?",
      "When did this occur and was it a one-time event or recurrent?",
      "Were you evaluated or treated?",
      "Do you have any current symptoms, restrictions, or limitations?",
    ]),
    h("3", "Stroke, TIA, or head injury?", [
      "Which event are you referring to?",
      "When did it occur?",
      "Were you hospitalized or treated?",
      "Do you have any lasting symptoms, restrictions, or limitations?",
      "Are you under any current follow-up?",
    ]),
    h("4", "Epilepsy, seizures, or other neurologic disorders?", [
      "What neurologic condition are you referring to?",
      "When were you diagnosed or when did it occur?",
      "Are you taking medication or receiving treatment?",
      "Do you have any current symptoms, restrictions, or limitations?",
    ]),
    h("5", "Eye or vision problems?", [
      "What eye or vision condition are you referring to?",
      "When was it diagnosed?",
      "Do you use glasses, contacts, or other correction?",
      "Are you receiving treatment or follow-up?",
      "Does it affect daily activities or work?",
    ]),
    h("6", "Ear, nose, throat problems; hearing loss; hoarseness?", [
      "What ENT condition are you referring to?",
      "What symptoms do you have?",
      "Are you receiving treatment?",
      "Does it affect hearing, communication, breathing, or daily activities?",
    ]),
    h("7", "Allergies or history of anaphylactic reaction?", [
      "What are you allergic to?",
      "What reaction do you have?",
      "Have you ever required emergency treatment?",
      "Do you carry epinephrine or use other treatment?",
      "Do you have any current restrictions or precautions?",
    ]),
    h("8", "Shortness of breath, asthma, or COPD?", [
      "Which condition are you referring to?",
      "When were you diagnosed?",
      "How often do symptoms occur and what triggers them?",
      "Are you taking medication or using an inhaler?",
      "Does it affect daily activities or work?",
    ]),
    h("9", "History of abnormal chest x-ray?", [
      "When was the abnormal chest x-ray?",
      "What did the provider tell you was abnormal?",
      "Did you receive additional testing or treatment?",
      "Is any follow-up still ongoing?",
    ]),
    h("10", "History of positive TB skin test, IGRA, or tuberculosis?", [
      "Are you referring to a positive test, latent TB, active TB, or prior treatment?",
      "When did this occur?",
      "Did you receive treatment?",
      "Do you have any current symptoms, monitoring, or follow-up needs?",
    ]),
    h("11", "Aneurysm, blood clot, or pulmonary embolism?", [
      "What condition are you referring to?",
      "When did it occur?",
      "Did you receive treatment or surgery?",
      "Are you taking blood thinners or under current follow-up?",
      "Do you have any current restrictions or limitations?",
    ]),
    h("12", "High blood pressure?", [
      "When were you told you had high blood pressure?",
      "Are you taking medication or receiving treatment?",
      "Do you know your recent blood pressure reading?",
      "Does it currently cause any symptoms, restrictions, or limitations?",
    ]),
    h("13", "Murmurs, palpitations, or other heart problems?", [
      "What heart condition are you referring to?",
      "When was it diagnosed?",
      "Are you receiving treatment or specialist follow-up?",
      "Do you currently have symptoms such as palpitations, chest pain, dizziness, fainting, or shortness of breath?",
      "Does it affect daily activities or work?",
    ]),
    h("14", "Are you a former or current smoker?", [
      "Are you a current smoker or former smoker?",
      "What tobacco products did or do you use?",
      "How much did or do you use?",
      "If former, when did you quit?",
      "Have you had any health effects related to smoking?",
    ]),
    h("15", "Stomach, esophageal, or other intestinal problems?", [
      "What GI condition are you referring to?",
      "When was it diagnosed or when did it occur?",
      "Did you receive treatment?",
      "Do you have any current symptoms, restrictions, or monitoring needs?",
    ]),
    h("16", "Jaundice, hepatitis, or other liver disease?", [
      "What liver condition or type of hepatitis are you referring to?",
      "When were you diagnosed?",
      "Did you receive treatment?",
      "Do you have any current symptoms, restrictions, or monitoring needs?",
    ]),
    h("17", "Intestinal, rectal problems, or hernia?", [
      "What condition are you referring to?",
      "When did it occur?",
      "Did you receive treatment or surgery?",
      "Do you have any current symptoms, restrictions, or limitations?",
    ]),
    h("18", "Urinary or kidney problems, blood in urine?", [
      "What condition are you referring to?",
      "When did it occur?",
      "Did you receive treatment?",
      "Do you have any current symptoms, restrictions, or monitoring needs?",
    ]),
    h("19", "Diabetes, thyroid, or other endocrine disorders?", [
      "What diagnosis are you referring to?",
      "When were you diagnosed?",
      "Are you receiving treatment or taking medication?",
      "Do you have any current symptoms, restrictions, complications, or monitoring needs?",
    ]),
    h("20", "Joint or back pain/injury?", [
      "What body area is affected?",
      "When did it occur?",
      "What treatment did you receive?",
      "Do you have any current pain, restrictions, limitations, or work impact?",
    ]),
    h("22", "Rheumatologic disorder?", [
      "What diagnosis are you referring to?",
      "What body areas are affected?",
      "Are you receiving treatment or taking medication?",
      "Does it cause any current symptoms, restrictions, or limitations?",
    ]),
    h("23", "Anemia?", [
      "When were you diagnosed with anemia?",
      "Are you receiving treatment or monitoring?",
      "Does it cause any current symptoms or limitations?",
    ]),
    h("24", "Blood transfusion?", [
      "When did you receive the blood transfusion?",
      "Why was it needed?",
      "Was it related to a condition that is still current or requires follow-up?",
    ]),
    h("25", "Malaria, tropical, or other infectious disease?", [
      "What infection are you referring to?",
      "When did it occur?",
      "Did you receive treatment?",
      "Are there any ongoing symptoms, restrictions, or monitoring needs?",
    ]),
    h("26", "Any skin or nail disorder?", [
      "What skin or nail condition are you referring to?",
      "Are you receiving treatment?",
      "Does it affect daily activities or work?",
    ]),
    h("27", "Cancer of any type?", [
      "What type of cancer did you have?",
      "When were you diagnosed?",
      "What treatment did you receive?",
      "Is the condition resolved, active, or under surveillance?",
      "Do you have any current restrictions or limitations?",
    ]),
    h("28", "Any thickening or lump in breast or testicle?", [
      "Where was the lump or thickening located?",
      "When was it identified?",
      "Was it evaluated by a provider?",
      "Was a diagnosis made?",
      "Is it still present or resolved?",
    ]),
    h("29", "Referred or evaluated for special educational services, accommodations, IFSP, IEP, or 504 plan?", [
      "What support or accommodation was involved?",
      "Is the need current?",
      "Does it affect learning, cognitive functioning, or daily activities now?",
    ]),
    h("30", "In the past two years, psychotherapy or counseling for mental or behavioral health concerns?", [
      "What condition or concern led to counseling or psychotherapy?",
      "Is treatment current?",
      "Are you taking medication?",
      "Do you have any current symptoms, restrictions, or limitations?",
    ]),
    h("31", "In the past two years, prescribed medication for depression, anxiety, mood, stress, memory/attention, or other behavioral symptoms?", [
      "What medication are you taking?",
      "What condition is it treating?",
      "Is the medication current?",
      "Do you have any side effects?",
      "Do you have any current symptoms, restrictions, or limitations related to the condition?",
    ]),
    h("32", "Alcohol or drug-related problem, advice to reduce use, or negative consequence due to substance use?", [
      "What substance-related issue are you referring to?",
      "When did it occur?",
      "Did you receive treatment or counseling?",
      "Does it currently affect your daily activities, work, or functioning?",
    ]),
    h("33", "Symptoms of an eating disorder?", [
      "What eating disorder symptoms or diagnosis are you referring to?",
      "Did you receive treatment?",
      "Do you have any current symptoms or health impacts?",
    ]),
    h("34", "In the past two years, mental-health hospitalization, self-injury, or suicidal behavior?", [
      "What event or condition are you referring to?",
      "When did it occur?",
      "Are you currently in treatment?",
      "Do you have any current symptoms, restrictions, or safety concerns?",
    ]),
    branch("35", "35 — Are you interested in a consultation with a Mental Health specialist on managing treatment overseas?", S, [
      "What condition or concern would you like support with?",
      "Are you currently receiving treatment or medication?",
      "Are there anticipated needs related to living or working overseas?",
    ]),
    h("36", "Is there any other medical or mental health condition not covered in questions 1–35?", [
      "What condition or issue are you referring to?",
      "When did it occur or when were you diagnosed?",
      "Did you receive treatment?",
      "Do you have any current symptoms, restrictions, limitations, or monitoring needs?",
    ]),

    branch("medications", "III — List of current medications (prescription, over-the-counter, vitamins, and herbs)", "Current Medications / Allergies", [
      "For each medication, what condition is it treating?",
      "What dose and frequency do you take?",
      "When did you start taking it?",
      "Do you have any side effects?",
    ], { answerType: "text", triggerValue: "*" }),
    text("allergies", "III — Drug or other allergies", "Current Medications / Allergies", false),
    branch("hospitalizations", "IV — Hospitalizations, operations, and medical evacuations", "Hospitalizations / Operations", [
      "What illness, operation, or event was involved?",
      "When did it occur?",
      "What treatment did you receive?",
      "Do you have any current symptoms, restrictions, or follow-up related to it?",
    ], { answerType: "text", triggerValue: "*", required: false }),
  ],
);
