import { branch, date, form, text } from "./definition-helpers";

const S = "ESCAPE Post Self-Certification";
const b = (key: string, label: string, prompts: string[]) => branch(key, `${key} — ${label}`, S, prompts);

export const ds6570Definition = form(
  "ds-6570-escape-post-self-certification",
  "DS-6570 — ESCAPE Post Self-Certification",
  "Adaptive self-certification interview for deployment to ESCAPE posts, preserving all 43 source-form risk questions and the recovered deployment-specific follow-up bank.",
  "U.S. Department of State DS-6570, 10-2019",
  [
    text("patient.name", "Patient printed name", "Identification", false),
    date("patient.dob", "Date of birth", "Identification", false),
    text("patient.id", "ID", "Identification", false),
    text("deployment.post", "Deployment destination / post", "Identification", false),

    b("1", "Any condition that prevents performing the duties described on page 1, including all physical tasks and wearing personal protective equipment (mask, helmet, body armor, and chemical/biological garments)?", [
      "What condition prevents or limits your ability to perform the required duties?",
      "What specific duties are affected?",
      "Does this condition affect your ability to wear PPE, move quickly, climb stairs, board vehicles, carry equipment, or work in a high-stress environment?",
      "Is the condition current?",
      "Has a provider recommended any restrictions or limitations?",
    ]),
    b("2", "Conditions that prohibit required immunizations or medications such as anti-malarials, chemical/biological antidotes, or chemoprophylactic antibiotics?", [
      "What condition prevents you from receiving required immunizations, anti-malarials, antidotes, prophylactic antibiotics, or similar medications?",
      "Which vaccine or medication is affected?",
      "Is this a permanent or temporary issue?",
      "Has a provider documented the contraindication?",
    ]),
    b("3", "Any condition requiring frequent clinical visits or ancillary tests, significant limitation of physical activity, or increased risk of illness, injury, or infection?", [
      "What condition requires frequent clinical visits, testing, or significant activity limitation?",
      "How often do you need follow-up visits or tests?",
      "What physical activity limitations do you have?",
      "Does this condition increase your risk of illness, injury, or infection in a deployed environment?",
    ]),
    b("4", "Any unresolved acute illness or injury that would impair duty performance during deployment?", [
      "What acute illness or injury is unresolved?",
      "When did it begin?",
      "What treatment are you currently receiving?",
      "How does it currently affect your duty performance?",
    ]),
    b("5", "Asthma with FEV1 < 50% predicted despite appropriate therapy, hospitalization in the last 12 months, or daily systemic steroid requirement?", [
      "When were you diagnosed with asthma?",
      "Do you currently have symptoms?",
      "Have you required hospitalization in the last 12 months?",
      "Are you using systemic steroids or other treatment?",
      "Does asthma affect your ability to work in heat, dust, pollution, or during exertion?",
    ]),
    b("6", "Seizure disorder within the last year or currently requiring anticonvulsant medication?", [
      "When was your last seizure or seizure-like event?",
      "Are you currently taking anticonvulsant medication?",
      "Do you have any restrictions, limitations, or specialist follow-up related to this condition?",
      "Would this affect safe deployment or emergency response?",
    ]),
    b("7", "Diabetes mellitus?", [
      "When were you diagnosed?",
      "What treatment or medication do you use?",
      "Do you know your most recent A1C or current control status?",
      "Do you have any diabetic complications or work restrictions?",
      "Would this require ongoing monitoring while deployed?",
    ]),
    b("8", "History of heat stroke?", [
      "When did the heat stroke occur?",
      "Was it a one-time event or recurrent issue?",
      "Do you have any lingering sensitivity or restrictions related to heat exposure?",
      "Has a provider advised any limitations?",
    ]),
    b("9", "Meniere's disease or other vertiginous/motion sickness disorder?", [
      "What diagnosis or symptom pattern are you referring to?",
      "How often do episodes occur and how severe are they?",
      "Do they affect balance, safety, vehicle transport, or work performance?",
      "Are you receiving treatment?",
    ]),
    b("10", "Renalithiasis (kidney stones), recurrent or currently symptomatic?", [
      "How many kidney stone episodes have you had?",
      "When was the most recent one?",
      "Did the stone pass naturally or require treatment?",
      "Are you under current treatment or monitoring?",
      "Do you have any current symptoms?",
    ]),
    b("11", "Obstructive sleep apnea (OSA)?", [
      "Were you formally diagnosed with sleep apnea?",
      "When were you diagnosed and have you had a sleep study?",
      "Do you use CPAP or other treatment?",
      "Do you currently have symptoms such as daytime sleepiness, fatigue, or concentration issues?",
      "Would this affect safe deployment?",
    ]),
    b("12", "History of clinically diagnosed traumatic brain injury (TBI) or concussion?", [
      "When did the TBI or concussion occur?",
      "Was it a single event or multiple events?",
      "Did you receive treatment or monitoring?",
      "Do you have any current symptoms, restrictions, or lingering effects?",
    ]),
    b("13", "Symptomatic coronary artery disease?", [
      "When was it diagnosed?",
      "What treatment or medication are you receiving?",
      "Do you currently have symptoms such as chest pain, shortness of breath, or exercise intolerance?",
      "Does it cause any restrictions, monitoring needs, or concerns for deployment?",
    ]),
    b("14", "Chronic cough or coughing up blood?", [
      "Are you referring to chronic cough, coughing up blood, or both?",
      "When did this occur?",
      "Is it current or resolved?",
      "Have you been evaluated or treated?",
      "Do you have any current symptoms or limitations?",
    ]),
    b("15", "Myocardial infarction within the past two years?", [
      "When did the heart attack occur?",
      "What treatment did you receive?",
      "Are you under current cardiology follow-up?",
      "Do you have any current symptoms, restrictions, or limitations?",
    ]),
    b("16", "CABG, coronary angioplasty, carotid endarterectomy, arterial stenting, or aneurysm repair within two years?", [
      "What procedure did you have?",
      "When was it performed?",
      "What condition led to the procedure?",
      "Are you under current specialist follow-up?",
      "Do you have any current symptoms, restrictions, or limitations?",
    ]),
    b("17", "Cardiac dysrhythmias or arrhythmias, symptomatic or requiring medication, electrophysiologic control, or an implantable defibrillator?", [
      "What arrhythmia or rhythm disorder are you referring to?",
      "When was it diagnosed?",
      "Are you taking medication or receiving treatment?",
      "Do you have symptoms such as palpitations, dizziness, fainting, or exercise intolerance?",
      "Does it cause any restrictions or monitoring needs?",
    ]),
    b("18", "Hypertension not controlled with medication or requiring frequent monitoring?", [
      "When were you diagnosed with hypertension?",
      "Are you currently taking medication?",
      "How often do you require monitoring?",
      "Do you know your recent blood pressure readings?",
      "Does it cause any current symptoms, restrictions, or limitations?",
    ]),
    b("19", "Heart failure or history of heart failure?", [
      "When were you diagnosed?",
      "Is this current or historical?",
      "Are you receiving treatment or monitoring?",
      "Do you have symptoms such as shortness of breath, swelling, or exercise intolerance?",
      "Does it cause any restrictions or limitations?",
    ]),
    b("20", "Morbid obesity (BMI > 40)?", [
      "Is this current?",
      "Has a provider recommended restrictions, monitoring, or treatment?",
      "Does your weight currently affect mobility, exertion, PPE use, or emergency performance?",
    ]),
    b("21", "Active or chronic blood-borne disease including Hepatitis B, Hepatitis C, or HIV?", [
      "What diagnosis are you referring to?",
      "Is it active, treated, or monitored?",
      "Are you receiving treatment now?",
      "Would this require ongoing monitoring while deployed?",
      "Do you have any current restrictions or limitations?",
    ]),
    b("22", "Active tuberculosis?", [
      "When were you diagnosed with active tuberculosis?",
      "What treatment are you receiving or did you receive?",
      "Is it current or resolved?",
      "Do you have any current symptoms, restrictions, or monitoring needs?",
    ]),
    b("23", "Untreated latent tuberculosis or currently under treatment?", [
      "Are you referring to untreated latent TB or treatment currently in progress?",
      "When was it identified?",
      "What treatment has been recommended or started?",
      "Do you have any current symptoms or follow-up requirements?",
    ]),
    b("24", "Vision loss?", [
      "What type of vision loss are you referring to?",
      "Is it current?",
      "Are you using corrective lenses or receiving treatment?",
      "Does it affect your ability to safely perform your duties or work in deployed conditions?",
    ]),
    b("25", "Refractive eye surgery in the last year?", [
      "What surgery did you have, and when was it performed?",
      "Have you fully recovered?",
      "Are you under current follow-up?",
      "Do you have any current vision limitations or restrictions?",
    ]),
    b("26", "Currently using ophthalmic steroid drops?", [
      "What condition are the drops treating?",
      "How often do you use them?",
      "Is the underlying condition current?",
      "Does it affect your vision or work performance?",
    ]),
    b("27", "PRK or LASIK within the past six months?", [
      "What procedure did you have, and when was it performed?",
      "Have you fully recovered?",
      "Are you under current follow-up?",
      "Do you have any current vision symptoms or restrictions?",
    ]),
    b("28", "Hearing loss?", [
      "What hearing issue are you referring to?",
      "Is it current?",
      "Do you use hearing aids or receive treatment?",
      "Does it affect communication, alarms, situational awareness, or work performance?",
    ]),
    b("29", "On-going dental or orthodontic work?", [
      "What dental or orthodontic treatment is ongoing?",
      "How often do you need follow-up care?",
      "Is there any current pain, restriction, or need that could affect deployment?",
    ]),
    b("30", "On-going cancer therapy?", [
      "What cancer is being treated?",
      "What therapy are you receiving?",
      "How often is treatment required?",
      "Does it currently cause symptoms, restrictions, or monitoring needs that would affect deployment?",
    ]),
    b("31", "Untreated precancerous lesions?", [
      "What lesion or condition are you referring to?",
      "When was it identified?",
      "Has treatment been recommended?",
      "Is it being monitored?",
      "Does it currently require follow-up care?",
    ]),
    b("32", "Any condition that requires surgery, or surgery requiring ongoing treatment, rehabilitation, hardware revision/removal, or additional surgery?", [
      "What condition or surgery are you referring to?",
      "When did it occur or when was surgery performed?",
      "Is treatment, rehabilitation, or additional surgery still needed?",
      "Do you have any current restrictions or limitations?",
    ]),
    b("33", "Open or laparoscopic surgery within the past six months?", [
      "What surgery did you have?",
      "When was it performed?",
      "Why was it needed?",
      "Have you fully recovered?",
      "Do you have any current symptoms, restrictions, or ongoing treatment?",
    ]),
    b("34", "Psychotic or bipolar disorders?", [
      "What diagnosis are you referring to?",
      "Is it current?",
      "Are you receiving psychiatric treatment, counseling, or medication?",
      "Do you have any current symptoms, restrictions, or monitoring needs?",
      "Would this affect safe deployment?",
    ]),
    b("35", "Clinical psychiatric disorders with residual symptoms or medication side effects?", [
      "What condition are you referring to?",
      "What residual symptoms or medication side effects do you currently have?",
      "Are you receiving treatment or taking medication?",
      "Do these symptoms or side effects affect your ability to work or deploy safely?",
    ]),
    b("36", "History of psychiatric hospitalization, suicide attempt, substance abuse/treatment, PTSD, or TBI?", [
      "Which history are you referring to?",
      "When did it occur?",
      "Is the issue current or historical?",
      "Are you receiving any treatment, counseling, or medication now?",
      "Do you have any current symptoms, restrictions, or monitoring needs?",
    ]),
    b("37", "Medications — blood modifiers?", [
      "What medication are you taking?",
      "What condition is it treating?",
      "Do you have any side effects?",
      "Does the condition or medication require monitoring during deployment?",
    ]),
    b("38", "Medications — antineoplastic (oncologic or nononcologic)?", [
      "What medication are you taking?",
      "What condition is it treating?",
      "Do you have any side effects or monitoring needs that could affect deployment?",
    ]),
    b("39", "Medications — immunosuppressants?", [
      "What medication are you taking?",
      "What condition is it treating?",
      "Do you have any side effects or increased infection risk that would affect deployment?",
    ]),
    b("40", "Medications — biologic response modifiers (immunomodulators)?", [
      "What medication are you taking?",
      "What condition is it treating?",
      "Do you have any side effects or monitoring needs that could affect deployment?",
    ]),
    b("41", "Medications — psychiatric or sleeping aids?", [
      "What medication are you taking?",
      "What condition is it treating?",
      "Do you have any side effects such as sedation, fatigue, or concentration issues?",
      "Would it affect safe deployment or work performance?",
    ]),
    b("42", "Medications — anticonvulsants?", [
      "What medication are you taking?",
      "What condition is it treating?",
      "Do you have any side effects or current restrictions related to the condition?",
    ]),
    b("43", "Medications — pain medications, opioids, or opioid combination drugs?", [
      "What medication are you taking?",
      "What condition is it treating?",
      "How often do you take it?",
      "Do you have any side effects such as sedation or impaired concentration?",
      "Does the underlying condition or medication affect your ability to deploy or work safely?",
    ]),
  ],
);
